### ISSUE TITLE
Is it necessary to have data on previous volume

### ISSUE THREAD

**Issue by pranavlal** [CanerIrfanoglu/medium#2]
Hi,
I am trying to modify these scripts to take in a csv file. I do not have data on opening volumes. 

Is that data crucial to have? 

I am attaching the csv file with this message.

[Quote-Equity-HDFCBANK-EQ-05-01-2020-to-05-01-2021.txt](https://github.com/CanerIrfanoglu/medium/files/5768855/Quote-Equity-HDFCBANK-EQ-05-01-2020-to-05-01-2021.txt)
b

**Comment by CanerIrfanoglu** [comment]
HI @pranavlal 

Volume data is returned as part of the cryptocompare API response when we use the OHLC end point. It is not used for calculating patterns. Your file looks good to me since it contains OHLC data.

Cheers,
Caner
