### ISSUE TITLE
How are bearish patterns identified?

### ISSUE THREAD

**Issue by Aqua-4** [CanerIrfanoglu/medium#5]
https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHAMMER.c#l246

According to documentation CDLHAMMER would always return bullish, which infers that `"CDLHAMMER_Bear": 65,` will never be true.

Please confirm.

**Comment by CanerIrfanoglu** [comment]
Hey @Aqua-4 

As indicated in `candle_rankings.py` not all patterns have bearish versions. Please see below.

```
# Note - 1
# Only some patterns have bull and bear versions. 
# However, to make the process unified and for codability purposes 
# all patterns are labeled with "_Bull" and "_Bear" tags.
```

I just checked and confirmed the Hammer is only bullish indeed, based on:
https://thepatternsite.com/Hammer.html
